# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: Reifurther
email: reifurther@outlook.com

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
markdown: kramdown
highlighter: rouge

disqus: reifurther
google_analytics: reifurther
gems: [jekyll-paginate]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: reifurther

description: My private blog.
author:
  name: reifurther
  email: reifurther@outlook.com
  github: reifurther
  twitter: reifurther
  pinterest: reifurther
  linkedin: reifurther
  bio: my live, my love!
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
